# Generated by Django 4.2.7 on 2026-02-18 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=15)),
                ('pan_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('company_certificate', models.FileField(blank=True, null=True, upload_to='documents/company/')),
                ('gst_certificate', models.FileField(blank=True, null=True, upload_to='documents/gst/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='documents/pan/')),
                ('bank_details', models.FileField(blank=True, null=True, upload_to='documents/bank/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
