# Generated by Django 6.0.2 on 2026-02-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tender_id", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=100)),
                ("boq_file", models.FileField(upload_to="boq_files/")),
                ("min_turnover", models.DecimalField(decimal_places=2, max_digits=15)),
                ("min_experience", models.IntegerField()),
                ("certificates", models.TextField()),
                ("manpower", models.CharField(max_length=100)),
                ("weight_price", models.IntegerField()),
                ("weight_experience", models.IntegerField()),
                ("weight_technical", models.IntegerField()),
                ("weight_performance", models.IntegerField()),
                ("last_date", models.DateField()),
                ("required_documents", models.TextField()),
                ("category", models.CharField(max_length=50)),
            ],
        ),
    ]
