# Generated by Django 6.0.2 on 2026-02-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_tender"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="required_certificates",
            field=models.TextField(default="GST, PAN", max_length=255),
        ),
    ]
