# Generated by Django 4.2.7 on 2026-02-18 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_bidder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iso_certification', models.CharField(blank=True, max_length=100)),
                ('security_clearance', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted')], default='Draft', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Infrastructure', 'Infrastructure'), ('IT Services', 'IT Services'), ('Healthcare', 'Healthcare'), ('Education', 'Education')], max_length=50)),
                ('description', models.TextField()),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BidDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bid_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app1.bid')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tender'),
        ),
    ]
