# Generated by Django 4.2.7 on 2026-02-19 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_bid_tender_biddocument_bid_tender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biddocument',
            name='bid',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='BidDocument',
        ),
        migrations.DeleteModel(
            name='Tender',
        ),
    ]
