# Generated by Django 4.2.7 on 2026-02-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_biddocument_bid_delete_bid_delete_biddocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bidder',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
