# Generated by Django 6.0.2 on 2026-02-18 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_tender_created_at_tender_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tender",
            name="required_certificates",
        ),
        migrations.AddField(
            model_name="tender",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tender",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="tender",
            name="certificates",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tender",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tender",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tender",
            name="manpower",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tender",
            name="min_experience",
            field=models.PositiveIntegerField(help_text="In years"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="required_documents",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tender",
            name="weight_experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tender",
            name="weight_performance",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tender",
            name="weight_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tender",
            name="weight_technical",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
