# Generated by Django 4.2.7 on 2026-02-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_bidder_email_bidder_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
