# Generated by Django 4.2.7 on 2026-02-19 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_tender_required_certificates_tender_status_and_more'),
        ('app1', '0006_alter_bidder_email'),
    ]

    operations = [
    ]
