# Generated by Django 4.2.7 on 2026-02-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_merge_20260219_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
